### PR TITLE
Update glossary search bar and plot parameters

### PR DESCRIPTION
**Pull request by reyery**
Fixes:
-
- Make glossary search bar only show more narrow results
https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2489
- Change buttons in data management tool options
https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2494
- Expand collapsed categories if errors are found inside
https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2500
- Refactoring of Parameters component
- Plot parameter options are more scenario specific when scenario changes
  - e.g. Changing scenario parameter will change building parameter to only show buildings that exist in the newly selected scenario

EDIT:
Upload build. https://we.tl/t-uBtiYTRQrl

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@reyery how does we test this. do we need a build?

**Comment by reyery** [comment]
You could run it in development mode by going to this branch and running `yarn dev`

**Comment by reyery** [comment]
Make glossary search bar only show more narrow results
    architecture-building-systems/CityEnergyAnalyst#2489
    Change buttons in data management tool options
    architecture-building-systems/CityEnergyAnalyst#2494
    Expand collapsed categories if errors are found inside
    architecture-building-systems/CityEnergyAnalyst#2500
    Refactoring of Parameters component
    Plot parameter options are more scenario specific when scenario changes
        e.g. Changing scenario parameter will change building parameter to only show buildings that exist in the newly selected scenario


Testing
- Typing queries in the glossary search bar should now only show results that **start** with the query and not **contains** anymore.
- Clicking data management tool option buttons should work as intended

> "Cancel": Closes the dialog, no changes are made, behavior is exactly the same as "Back"
>
> "Load default settings": All the parameters are set to the default.config values, behavior is exactly the same as "Default" - we could also just leave this button, but change the position
>
>"Save & Close": In addition to the "Save to Config" behavior, the dialog should close.
- Rename `Daysim` folder and try to run `radiation` script. Collapsed panels containing parameter errors will expand

**Comment by daren-thomas** [comment]
works as intended :)

**Pull request merged**
