### PR TITLE
Add log function

### PR DESCRIPTION
**Pull request by reyery**
This solves https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2795

It logs all console outputs and errors and writes them to a log file.

By default, it writes logs to the following locations:
- on Linux: ~/.config/CityEnergyAnalyst-GUI/logs/console.log
- on macOS: ~/Library/Logs/CityEnergyAnalyst-GUI/console.log
- on Windows: %USERPROFILE%\AppData\Roaming\CityEnergyAnalyst-GUI\logs\console.log

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
thanks for the PR, @reyery ! how can I test it?

**Comment by reyery** [comment]
@shanshanhsieh You would have to build the new GUI from this branch and just launch it. Open a scenario and run some scripts, and the log file should appear in the path as mentioned above. 

e.g. on Windows: %USERPROFILE%\AppData\Roaming\CityEnergyAnalyst-GUI\logs\console.log

**Comment by shanshanhsieh** [comment]
@reyery , thanks for the hint, everything works on my side, but maybe some information could make the function more visible.

Is it possible to display the information on errors in the GUI?
For example, after *Something went wrong*, add instruction to find the `console.log` and then a msg to ask the user to post an issue on GitHub.
image

And a side note, there should be an input parameter check for the `weather` in the `Create Scenario` task.
That's the most common error that I think we could avoid ; )

**Comment by reyery** [comment]
Ah yes that's a great idea. I shall add that function in.

**Comment by shanshanhsieh** [comment]
@reyery , any update on this?

**Pull request merged**
